on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build --ws --if-present
      - name: Build
        run: npm run test --ws --if-present
      - name: Publish Editor
        run: npm publish -w graphql-editor --access public
      - name: Publish Editor Worker
        run: npm publish -w graphql-editor-worker --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
